"""Add attempts column to OTPLogin

Revision ID: fd590f729355
Revises: 3d5bac31461a
Create Date: 2026-04-19 18:37:00.120206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd590f729355'
down_revision = '3d5bac31461a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_login', schema=None) as batch_op:
        batch_op.drop_column('attempts')

    # ### end Alembic commands ###
